### ISSUE TITLE
Turn off overlays by default

### ISSUE THREAD

**Issue by hedning** [Mic92/nix-review#29]
When reviewing a change we most likely don't want to use local overlays as it can give false results.

I ran into this due to suddenly getting an error from an overlay, tried to pass `--args overlays []` as a build-arg, but that didn't work as I guess the flags aren't used when generating the build list.

**Comment by Mic92** [comment]
Does this fix your problem? https://github.com/Mic92/nix-review/pull/30

**Comment by Mic92** [comment]
`--build-args` are currently not passed to `nix-shell`, which is a bug.

**Comment by Mic92** [comment]
However I should probably have different flags for `nix-shell`, `nix build` and both.

**Comment by hedning** [comment]
Hmm, that's weird it doesn't for some reason.

Here's the error:
> error: while evaluating 'callPackageWith' at /home/hed/.cache/nix-review/rev-46352d5e95ee7766398f7298527707b79f6b5852/nixpkgs/lib/customisation.nix:113:35, called from /home/hed/src/nixpkgs-mozilla/vidyo-overlay.nix:4:18:
while evaluating 'makeOverridable' at /home/hed/.cache/nix-review/rev-46352d5e95ee7766398f7298527707b79f6b5852/nixpkgs/lib/customisation.nix:72:24, called from /home/hed/.cache/nix-review/rev-46352d5e95ee7766398f7298527707b79f6b5852/nixpkgs/lib/customisation.nix:117:8:
anonymous function at /home/hed/src/nixpkgs-mozilla/pkgs/VidyoDesktop/default.nix:1:1 called without required argument 'libGL', at /home/hed/.cache/nix-review/rev-46352d5e95ee7766398f7298527707b79f6b5852/nixpkgs/lib/customisation.nix:74:12

**Comment by Mic92** [comment]
So did you use ./bin/nix-review from the repository for that?
I don't see any other way this could be passed to nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/impure.nix#L42

Does something tries to re-import nixpkgs?

**Comment by hedning** [comment]
Yeah, tried with `~/path/to/bin/nix-review` and nix-env

**Comment by Mic92** [comment]
Ah. I see. nix-env would bypass that. How about the following: https://github.com/Mic92/nix-review/pull/31

**Comment by hedning** [comment]
Yes, that worked.

Thanks :)
