### ISSUE TITLE
Feature request: option for not using ofborg cache

### ISSUE THREAD

**Issue by dotlambda** [Mic92/nix-review#4]
I want to review NixOS/Nixpkgs#42854, but it fails because one of the packages that need to be rebuilt after that PR has since been dropped from Nixpkgs. It would be nice to have the option of not using ofborg cache in such cases.

**Comment by Mic92** [comment]
An option could be added here: https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L30
and the resulting flag used in a conditional here: https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L58

**Comment by dotlambda** [comment]
I'll do that. How would you call the flag?

**Comment by Mic92** [comment]
How about `--eval=ofborg|local`? 
Please also add a short description here: https://github.com/Mic92/nix-review#remote-builder

**Comment by dotlambda** [comment]
What does this have to do with remote builders?
