### ISSUE TITLE
show trace ?

### ISSUE THREAD

**Issue by teto** [Mic92/nix-review#42]
I am trying to debug locally the problem met by: 
`https://gist.github.com/GrahamcOfBorg/2b89c7fce733a4cd8878f44d924bf2c2`

The same error triggers locally but I miss the trace compared to ofborg's output ?
```
$ git merge --no-commit 916a57dce6d33840edb0efe5c360505edfe92a81
Fusion automatique de pkgs/top-level/lua-packages.nix
Fusion automatique de pkgs/top-level/all-packages.nix
La fusion automatique a réussi ; stoppée avant la validation comme demandé
error: infinite recursion encountered, at /home/teto/.cache/nix-review/rev-916a57dce6d33840edb0efe5c360505edfe92a81/nixpkgs/pkgs/top-level/lua-packages.nix:64:13
```

Another question/request: would it be possible to review uncommitted changes ? I would like to avoid committing when locally iterating on the PR.

Btw: congrats on disabling overlays, I really missed that in nox review.

**Comment by Mic92** [comment]
It should show a trace, but for infinite recursion you usually don't get one,
beyond the line that is currently printed: https://github.com/Mic92/nix-review/blob/3e3b4ee39d361bef9f1d395abad1c34ad439a981/nix_review/review.py#L127
The trace of ofBorg comes from its evaluation script it is using and is just noise added. I have not yet figured out how to add uncommitted changes to a `git-worktree`.

**Comment by teto** [comment]
> The trace of ofBorg comes from its evaluation script it is using and is just noise added.

I managed to find the cause of the bug thanks to this

>  how to add uncommitted changes to a git-worktree

isn't it possible to stash/unstash in a different working tree ?

**Comment by Mic92** [comment]
Reviewing uncommitted changes is now also supported using the `wip` subcommand: https://github.com/Mic92/nix-review#usage

**Comment by teto** [comment]
cool thanks
