### ISSUE TITLE
High memory usage of nix-review

### ISSUE THREAD

**Issue by costrouc** [Mic92/nix-review#60]
Maybe not an issue since nix-review is possibly smart. I have 8 GB of ram on my laptop. Nix-review often times takes up 7+ GB of ram. This may be an issue as nixpkgs gets larger?

**Comment by Mic92** [comment]
Yeah, nix-review tries to rely on ofborg's evaluation to get a package list. However if ofborg is not ready evaluating it fallback to local evaluation. There is little I can do about that.

**Comment by costrouc** [comment]
Completely fine with me. I will make sure to run the tests on a higher memory machine. This reminds me of the same issues of evaluating all the meta attributes of nixpkgs.

**Comment by Mic92** [comment]
Maybe this option could be used to not evaluate all meta attributes: https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L152

I initially added this option to check for evaluation errors.

**Comment by costrouc** [comment]
This is great. `nix-review` has saved me days -- thanks for all the work.

**Comment by Mic92** [comment]
Should we have this as a default?

**Comment by costrouc** [comment]
If it doesn't add to the evaluation time it could certainly help with getting quicker feedback. I often run nix-review on HEAD and don't want to wait for gramcofborg bot to tell me that a meta attribute is incorrect

**Comment by Mic92** [comment]
It might increase memory usage, I have not checked.

**Comment by Quantenzitrone** [comment]
i have like 15.5GiB, and `nixpkgs-review` still needed to swap quite a bit, well

**Comment by Mic92** [comment]
Yeah I was playing around with nix-eval-jobs the other day but just now it's signicantly slower than nix-env. Have to check why this is the case. Than I could have it restart if there is too much memory usage and allow also people with normal sized laptops to do local eval.
