### ISSUE TITLE
nix-review needs to turn off fetch.prune when fetching PR

### ISSUE THREAD

**Issue by lilyball** [Mic92/nix-review#62]
When running the `git fetch` command to fetch the PR, nix-review really needs to specify `git -c fetch.prune=false fetch`. Otherwise if I've already run `nix-review` before, it fails and requires re-running again to succeed.

The failure is because the `fetch.prune` setting causes git to delete the local `refs/nix-review/0` and `refs/nix-review/1` refs in the same fetch that it's then trying to update those, and this produces an error. Right now I'm getting "fatal: Needed a single revision" but in the past I've seen errors about not being able to acquire the lock for `refs/nix-review/0` (I'm guessing there's some race condition between pruning the ref and updating it). This is clearly a bug in git itself, but nix-review should be able to work around it.

This issue occurs when my global config has `fetch.prune` set to `true`.

**Comment by Mic92** [comment]
With this option, the error message will be no longer shown?

**Comment by lilyball** [comment]
It should be, but I haven't tried patching `nix-review` to confirm.

What I do know is if I run `git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/66947/head:refs/nix-review/1` by hand, it alternates between fetching the refs and deleting them, but `git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/66947/head:refs/nix-review/1` repeatedly works.

---

For reference, the "fatal: Needed a single revision" means the `git fetch` didn't error out, but the refs didn't exist anymore, and the error message is presumably coming from a subsequent `git` command. I think this happens if `git` already had the commits locally and didn't have to fetch anything. If it does fetch from remote (when the refs existed first), then the `git fetch` errors out with "cannot lock ref" as mentioned. That looks like

```
> git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/66949/head:refs/nix-review/1
From https://github.com/NixOS/nixpkgs
 - [deleted]                 (none)     -> refs/nix-review/0
 - [deleted]                 (none)     -> refs/nix-review/1
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 7 (delta 3), reused 3 (delta 3), pack-reused 4
Unpacking objects: 100% (7/7), done.
error: cannot lock ref 'refs/nix-review/1': unable to resolve reference 'refs/nix-review/1'
 ! 491ed6ca1d7...bd4338946a0 refs/pull/66949/head -> refs/nix-review/1  (unable to update local ref)
```

Again, this is very clearly a `git` bug, but one I doubt they're going to fix any time soon, so `nix-review` should just apply the simple workaround of `git -c fetch.prune=false fetch --force …`

**Comment by Mic92** [comment]
Should be fixed by: https://github.com/Mic92/nix-review/pull/64
