### ISSUE TITLE
Rename to nixpkgs-review?

### ISSUE THREAD

**Issue by zimbatm** [Mic92/nix-review#66]
This is messing up with my OCD. This tool is about reviewing nixpkgs only! :D

**Comment by Mic92** [comment]
Makes sense. Also people might get a bit refused in the meantime.

**Comment by Mic92** [comment]
I would wait for a new release though before renaming.

**Comment by zimbatm** [comment]
thanks for considering :)

**Comment by Mic92** [comment]
This one also would needed to be updated: https://github.com/spwhitt/nix-zsh-completions/blob/master/_nix-review

**Comment by davidak** [comment]
Good idea. Would also be consistent with [nixpkgs-update](https://github.com/ryantm/nixpkgs-update).
