### ISSUE TITLE
[feat] Build reports

### ISSUE THREAD

**Issue by zimbatm** [Mic92/nix-review#67]
It would be cool if the tool would generate a markdown report that can be copy-and-pasted onto the PR. Or even appended as a comment automatically.

**Comment by Mic92** [comment]
This is already implemented:

```
$ nix-review pr 68943
$ cat report.md
Result of `nix-review pr 68943` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - helmfile
</details>
```

Result of `nix-review pr 68943` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - helmfile
</details>

**Comment by Mic92** [comment]
https://github.com/Mic92/nix-review/pull/37/files
