### ISSUE TITLE
Trying to review linux builds on osx with remote build fails

### ISSUE THREAD

**Issue by tricktron** [Mic92/nix-review#72]
I am on OSX Catalina and I try to review if my own [pull request](https://github.com/NixOS/nixpkgs/pull/71318) regarding openconnet also works on linux by using [linuxkit-nix](https://github.com/nix-community/linuxkit-nix) and nix-review:
```bash
nix-shell -p nix-review
nix-review pr --build-args="--builders ssh://root@nix-linuxkit --argstr system x86_64-linux" 71318
```

Unfortunately it fails with the error:
```bash
build of '/nix/store/7g2nsd32plad8ipnqii5z2qivfl7mjjq-bash-completion-2.9.drv'
on 'ssh://root@nix-linuxkit' failed: a 'x86_64-darwin' is required to build
'/nix/store/7g2nsd32plad8ipnqii5z2qivfl7mjjq-bash-completion-2.9.drv', but I am a ### 'x86_64-linux'
```

If I try it with the ```--option``` arg:
```nix-review pr --build-args="--builders ssh://root@nix-linuxkit --option system x86_64-linux" 71318```

it fails silently by somehow skipping the build because I get the following output:

```
7 package are marked as broken and were skipped
connman_dmenu gnome3.nautilus-python libsForQt5.alkimia
libsForQt511.alkimia libsForQt512.alkimia networkmanager_dmenu strongswanNM

2 package failed to build:
openconnect openconnect_openssl
```

Possibly related issues who tried the same using [nix-docker](https://github.com/LnL7/nix-docker).

Using just ```build --option build-use-sandbox true --argstr system x86_64-linux -A openconnect``` works just fine.

**Comment by tricktron** [comment]
It was a problem related to the `bash-completion-2.9` derivation. So I am going to close this here now.

**Comment by Mic92** [comment]
Note that for remote builders crossing architectures we only build packages for the current system and not the system that you set with `--build-args`:

https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L26

We need a proper `--system` flag to cover that.

**Comment by tricktron** [comment]
Thanks for the answer. How would you achieve such a proper `--system` flag?

**Comment by Mic92** [comment]
The value needs to be passed to https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L160 and https://github.com/Mic92/nix-review/blob/master/nix_review/review.py#L30 so both returns the packages for the target system and not the system `nix-review` is running on.
